redbean:
    namespace: Pizza\Model\

admin:
    root: pizza.list

locale: en
full_locale: en_GB.UTF8
timezone: Europe/London
title: Patchwork
description: '#PHP 5.4+ web framework powered by #Composer #Silex #RedBean #NPM'